In [148]:
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [149]:
iris = pd.read_csv('../data/iris.csv')

In [150]:
mask= iris['variety']=='Setosa'

In [151]:
target = iris[iris.columns[-1]]
feature = iris[iris.columns[:4]]

In [152]:
feature.head(2)

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2

In [153]:
target.head(2)

target = target.replace({'Setosa':0, 'Versicolor':1, 'Virginica':2 })
target = pd.DataFrame(target)

In [154]:
from sklearn.model_selection import train_test_split

In [155]:
xtrain, xtest, ytrain, ytest = train_test_split(feature, target, test_size = 0.2, random_state = 0)

In [156]:
from sklearn.preprocessing import StandardScaler

In [157]:
ss = StandardScaler()
ss.fit(xtrain)
ss.fit(xtest)

StandardScaler()

In [158]:
xtrain = ss.transform(xtrain)
xtest = ss.transform(xtest)

In [159]:
svc = SVC(kernel = 'linear', C=0.01)
svc.fit(xtrain, ytrain)

C:\Users\kdp\anaconda3\envs\EXAM_ML\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=0.01, kernel='linear')

In [160]:
print(f'test: {svc.score(xtest, ytest)}, train; {svc.score(xtrain, ytrain)}')

test: 0.8333333333333334, train; 0.875


In [161]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [162]:
ypred = svc.predict(xtest)

In [163]:
f1score = f1_score(ytest, ypred, average = 'weighted')
accuracy = accuracy_score(ytest, ypred)
precision = precision_score(ytest, ypred, average = 'weighted')
recall = recall_score(ytest, ypred, average = 'weighted')
cm = confusion_matrix(ytest, ypred)
rpt = classification_report(ytest, ypred)


In [164]:
print(f'[f1score] : {f1score}\n[accuracy] : {accuracy}\n[precision] : {precision}')
print(f'[recall] : {recall}\n[confusion matrix] :\n{cm}')
print('-'*30,'report','-'*30)
print(rpt)

[f1score] : 0.8380018674136321
[accuracy] : 0.8333333333333334
[precision] : 0.9090909090909091
[recall] : 0.8333333333333334
[confusion matrix] :
[[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]
------------------------------ report ------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.62      0.76        13
           2       0.55      1.00      0.71         6

    accuracy                           0.83        30
   macro avg       0.85      0.87      0.82        30
weighted avg       0.91      0.83      0.84        30


In [166]:
predict_proba = svc.predict_proba(xtest, probability=True)

AttributeError: predict_proba is not available when  probability=False